#!/usr/bin/python3

"""Write a class Rectangle that defines a rectangle by: (based on 0-rectangle.py"""

class Rectangle:
    """rectangle class"""
    def __init__(self, width=0, height=0):
        """ Initializer"""
    
